require 'capybara/guides/engine'
require 'capybara/guides/version'
require 'capybara/rspec/matchers'
require 'capybara/guides/rspec_helpers'
require 'capybara/guides/capybara_node_base_decorator'
require 'capybara/guides/capybara_session_decorator'
require 'capybara/guides/rspec_config'
require 'capybara/guides/rspec_matchers_decorator'
